"""UPdating the ondelet cascade 

Revision ID: 16bd365092db
Revises: ee78cd4d53e8
Create Date: 2025-12-03 09:36:46.412001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16bd365092db'
down_revision: Union[str, Sequence[str], None] = 'ee78cd4d53e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('company_user_roles_company_user_id_fkey'), 'company_user_roles', type_='foreignkey')
    op.drop_constraint(op.f('company_user_roles_role_id_fkey'), 'company_user_roles', type_='foreignkey')
    op.create_foreign_key(None, 'company_user_roles', 'company_users', ['company_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'company_user_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('role_permissions_permission_id_fkey'), 'role_permissions', type_='foreignkey')
    op.drop_constraint(op.f('role_permissions_role_id_fkey'), 'role_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'role_permissions', 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'role_permissions', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('role_permissions_role_id_fkey'), 'role_permissions', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(op.f('role_permissions_permission_id_fkey'), 'role_permissions', 'permissions', ['permission_id'], ['id'])
    op.drop_constraint(None, 'company_user_roles', type_='foreignkey')
    op.drop_constraint(None, 'company_user_roles', type_='foreignkey')
    op.create_foreign_key(op.f('company_user_roles_role_id_fkey'), 'company_user_roles', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(op.f('company_user_roles_company_user_id_fkey'), 'company_user_roles', 'company_users', ['company_user_id'], ['id'])
    # ### end Alembic commands ###
